import 'dotenv/config';
import express, { NextFunction, Request, Response } from 'express';
import cors from 'cors';
import jwt from 'jsonwebtoken';
import bcrypt from 'bcryptjs';
import { z } from 'zod';
import { checkDatabaseConnection } from './db';

const app = express();
const allowedOrigins=(process.env.FRONTEND_URL||'http://localhost:5173,http://localhost:5174,http://localhost:5175').split(',').map(origin=>origin.trim());
app.use(cors({origin:(origin,callback)=>{if(!origin||allowedOrigins.includes(origin))return callback(null,true);return callback(new Error('Origin not allowed by CORS'));},methods:['GET','POST','PUT','PATCH','DELETE','OPTIONS'],allowedHeaders:['Content-Type','Authorization']}));
app.use(express.json());
const SECRET = process.env.JWT_SECRET || 'development-secret-change-me';
const PORT = Number(process.env.PORT || 4000);
type Role = 'Admin' | 'Sales' | 'Warehouse' | 'Accounts';
type User = { id: string; name: string; email: string; password: string; role: Role };
type Customer = { id:string; name:string; mobile:string; email:string; businessName:string; gst?:string; type:'Retail'|'Wholesale'|'Distributor'; address:string; status:'Lead'|'Active'|'Inactive'; followUpDate?:string; notes:string; followUps:{id:string; note:string; date:string; by:string}[] };
type Product = { id:string; name:string; sku:string; category:string; unitPrice:number; stock:number; minStock:number; location:string };
type Movement = { id:string; productId:string; quantity:number; type:'IN'|'OUT'; reason:string; createdBy:string; createdAt:string };
type Challan = { id:string; number:string; customerId:string; items:{productId:string; name:string; sku:string; price:number; quantity:number}[]; status:'Draft'|'Confirmed'|'Cancelled'; createdBy:string; createdAt:string };
const users:User[] = [
 {id:'u1',name:'Aarav Admin',email:'admin@acme.test',password:'admin123',role:'Admin'}, {id:'u2',name:'Maya Sales',email:'sales@acme.test',password:'sales123',role:'Sales'}, {id:'u3',name:'Rohan Warehouse',email:'warehouse@acme.test',password:'warehouse123',role:'Warehouse'}, {id:'u4',name:'Nina Accounts',email:'accounts@acme.test',password:'accounts123',role:'Accounts'}
];
const customers:Customer[]=[
 {id:'c1',name:'Priya Shah',mobile:'9876543210',email:'priya@urbanmart.in',businessName:'UrbanMart Retail',gst:'27AABCU9603R1ZX',type:'Retail',address:'Andheri East, Mumbai',status:'Active',followUpDate:'2026-08-14',notes:'Prefers morning deliveries.',followUps:[{id:'f1',note:'Confirm festive order quantities.',date:'2026-08-08',by:'Maya Sales'}]},
 {id:'c2',name:'Karan Mehta',mobile:'9811122233',email:'karan@mehtafoods.in',businessName:'Mehta Foods',type:'Wholesale',address:'Bhiwandi, Maharashtra',status:'Lead',followUpDate:'2026-08-12',notes:'Interested in monthly credit terms.',followUps:[]},
 {id:'c3',name:'Sonal Verma',mobile:'9900011122',email:'sonal@northstar.in',businessName:'Northstar Distribution',gst:'29AACCN7200F1Z2',type:'Distributor',address:'Whitefield, Bengaluru',status:'Active',notes:'Regional distributor.',followUps:[]}
];
const products:Product[]=[
 {id:'p1',name:'Premium Copier Paper A4',sku:'PAPER-A4-80',category:'Office Supplies',unitPrice:325,stock:225,minStock:80,location:'Mumbai A-12'},
 {id:'p2',name:'Thermal Receipt Roll',sku:'ROLL-80MM',category:'POS Supplies',unitPrice:48,stock:34,minStock:50,location:'Mumbai B-03'},
 {id:'p3',name:'Packing Tape 48mm',sku:'TAPE-48-CLR',category:'Packaging',unitPrice:62,stock:180,minStock:60,location:'Mumbai C-08'}
];
const movements:Movement[]=[{id:'m1',productId:'p1',quantity:240,type:'IN',reason:'Opening inventory',createdBy:'Aarav Admin',createdAt:'2026-08-01T09:00:00Z'},{id:'m2',productId:'p1',quantity:15,type:'OUT',reason:'Confirmed challan CH-2026-0001',createdBy:'Maya Sales',createdAt:'2026-08-08T10:30:00Z'}];
const challans:Challan[]=[
 {id:'ch1',number:'CH-2026-0001',customerId:'c1',items:[{productId:'p1',name:'Premium Copier Paper A4',sku:'PAPER-A4-80',price:325,quantity:15}],status:'Confirmed',createdBy:'Maya Sales',createdAt:'2026-08-08T10:30:00Z'},
 {id:'ch2',number:'CH-2026-0002',customerId:'c3',items:[{productId:'p3',name:'Packing Tape 48mm',sku:'TAPE-48-CLR',price:62,quantity:20}],status:'Draft',createdBy:'Maya Sales',createdAt:'2026-08-09T08:45:00Z'}
];
declare global { namespace Express { interface Request { user?: User } } }
const uid=(p:string)=>`${p}_${Math.random().toString(36).slice(2,9)}`;
const auth=(roles?:Role[]) => (req:Request,res:Response,next:NextFunction) => { try { const token=req.headers.authorization?.replace('Bearer ',''); if(!token) throw Error(); const payload=jwt.verify(token,SECRET) as {id:string}; const user=users.find(u=>u.id===payload.id); if(!user || (roles && !roles.includes(user.role))) return res.status(403).json({error:'You do not have permission for this action.'}); req.user=user; next(); } catch { res.status(401).json({error:'Authentication required.'}); } };
const customerSchema=z.object({name:z.string().min(2),mobile:z.string().trim().regex(/^\+?[0-9][0-9\s-]{7,14}$/,'Enter a valid mobile number.'),email:z.email(),businessName:z.string().min(2),gst:z.string().trim().toUpperCase().regex(/^[0-9A-Z]{15}$/,'GST must be a valid 15-character GSTIN.').optional().or(z.literal('')),type:z.enum(['Retail','Wholesale','Distributor']),address:z.string().min(5),status:z.enum(['Lead','Active','Inactive']),followUpDate:z.string().date().optional().or(z.literal('')),notes:z.string().default('')});
const productSchema=z.object({name:z.string().min(2),sku:z.string().min(2),category:z.string().min(2),unitPrice:z.number().positive(),stock:z.number().int().min(0),minStock:z.number().int().min(0),location:z.string().min(2)});
app.get('/health',async(_,res)=>{try{await checkDatabaseConnection();res.json({status:'ok',database:'connected',storage:'PostgreSQL connection active; demo records are currently in memory'});}catch{res.status(503).json({status:'unavailable',database:'connection failed'});}});
app.post('/auth/login',async(req,res)=>{ const parsed=z.object({email:z.email(),password:z.string().min(1)}).safeParse(req.body); if(!parsed.success) return res.status(400).json({error:'A valid email and password are required.'}); const user=users.find(u=>u.email===parsed.data.email); const valid=!!user && (user.password===parsed.data.password || await bcrypt.compare(parsed.data.password,user.password)); if(!valid || !user) return res.status(401).json({error:'Invalid email or password.'}); const token=jwt.sign({id:user.id,role:user.role},SECRET,{expiresIn:'8h'}); const {password,...safe}=user; res.json({token,user:safe}); });
app.post('/auth/register',async(req,res)=>{const parsed=z.object({name:z.string().trim().min(2,'Name must be at least 2 characters.'),email:z.email().transform(v=>v.toLowerCase()),password:z.string().min(8,'Password must be at least 8 characters.'),role:z.enum(['Admin','Sales','Warehouse','Accounts'])}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:parsed.error.issues[0].message});if(users.some(u=>u.email===parsed.data.email))return res.status(409).json({error:'An account with this email already exists.'});const user:User={id:uid('u'),name:parsed.data.name,email:parsed.data.email,password:await bcrypt.hash(parsed.data.password,10),role:parsed.data.role};users.push(user);const token=jwt.sign({id:user.id,role:user.role},SECRET,{expiresIn:'8h'});const {password,...safe}=user;res.status(201).json({token,user:safe,message:'Account created successfully.'});});
app.get('/dashboard',auth(),(_,res)=>res.json({customers:customers.length,activeCustomers:customers.filter(c=>c.status==='Active').length,products:products.length,lowStock:products.filter(p=>p.stock<=p.minStock).length,challans:challans.length,recentMovements:movements.slice(-5).reverse()}));
app.get('/dashboard/:role',auth(),(req,res)=>{
 const requested=String(req.params.role).toLowerCase(); const role=req.user!.role.toLowerCase();
 if(requested!==role && req.user!.role!=='Admin') return res.status(403).json({error:'You do not have permission to view this dashboard.'});
 const recentCustomers=customers.slice(-5).reverse(); const recentChallans=challans.slice(-5).reverse();
 const confirmed=challans.filter(c=>c.status==='Confirmed'); const drafts=challans.filter(c=>c.status==='Draft'); const cancelled=challans.filter(c=>c.status==='Cancelled');
 const today=new Date().toISOString().slice(0,10); const followUps=customers.flatMap(c=>c.followUps.map(f=>({...f,customer:c.name,business:c.businessName,status:c.status}))).filter(f=>f.date===today || customers.find(c=>c.name===f.customer)?.followUpDate===today);
 const common={recentCustomers,recentChallans,statusSummary:{draft:drafts.length,confirmed:confirmed.length,cancelled:cancelled.length}};
 if(requested==='sales') return res.json({...common,totalCustomers:customers.length,activeCustomers:customers.filter(c=>c.status==='Active').length,leads:customers.filter(c=>c.status==='Lead').length,todayFollowUps:followUps, draftChallans:drafts.length,confirmedChallans:confirmed.length});
 if(requested==='warehouse') return res.json({...common,totalProducts:products.length,totalStockUnits:products.reduce((sum,p)=>sum+p.stock,0),lowStockItems:products.filter(p=>p.stock>0&&p.stock<=p.minStock),outOfStockItems:products.filter(p=>p.stock===0),todayStockIn:movements.filter(m=>m.type==='IN'&&m.createdAt.startsWith(today)).reduce((sum,m)=>sum+m.quantity,0),todayStockOut:movements.filter(m=>m.type==='OUT'&&m.createdAt.startsWith(today)).reduce((sum,m)=>sum+m.quantity,0),products,recentMovements:movements.slice(-8).reverse()});
 if(requested==='accounts') return res.json({...common,totalChallans:challans.length,confirmedChallans:confirmed.length,draftChallans:drafts.length,cancelledChallans:cancelled.length,totalQuantitySold:confirmed.flatMap(c=>c.items).reduce((sum,i)=>sum+i.quantity,0)});
 return res.json({...common,totalCustomers:customers.length,totalProducts:products.length,currentStock:products.reduce((sum,p)=>sum+p.stock,0),lowStockItems:products.filter(p=>p.stock<=p.minStock),totalChallans:challans.length,confirmedChallans:confirmed.length,recentMovements:movements.slice(-5).reverse()});
});
app.get('/customers',auth(),(req,res)=>{const q=String(req.query.search||'').toLowerCase();const filtered=customers.filter(c=>!q||[c.name,c.businessName,c.mobile,c.email].some(v=>v.toLowerCase().includes(q)));const page=Math.max(1,Number(req.query.page)||1), limit=Math.min(100,Math.max(1,Number(req.query.limit)||50));res.json({data:filtered.slice((page-1)*limit,page*limit),pagination:{page,limit,total:filtered.length,totalPages:Math.max(1,Math.ceil(filtered.length/limit))}});});
app.get('/customers/:id',auth(),(req,res)=>{const c=customers.find(x=>x.id===req.params.id);return c?res.json(c):res.status(404).json({error:'Customer not found.'});});
app.post('/customers',auth(['Admin','Sales']),(req,res)=>{const p=customerSchema.safeParse(req.body);if(!p.success)return res.status(400).json({error:p.error.issues[0].message});const c:Customer={...p.data,id:uid('c'),followUps:[]};customers.push(c);res.status(201).json(c)});
app.put('/customers/:id',auth(['Admin','Sales']),(req,res)=>{const i=customers.findIndex(x=>x.id===req.params.id),p=customerSchema.safeParse(req.body);if(i<0)return res.status(404).json({error:'Customer not found.'});if(!p.success)return res.status(400).json({error:p.error.issues[0].message});customers[i]={...customers[i],...p.data};res.json(customers[i])});
app.post('/customers/:id/follow-ups',auth(['Admin','Sales']),(req,res)=>{const c=customers.find(x=>x.id===req.params.id);const p=z.object({note:z.string().min(2),date:z.string().min(8)}).safeParse(req.body);if(!c)return res.status(404).json({error:'Customer not found.'});if(!p.success)return res.status(400).json({error:'A note and date are required.'});const f={id:uid('f'),...p.data,by:req.user!.name};c.followUps.unshift(f);c.followUpDate=p.data.date;res.status(201).json(f)});
app.get('/products',auth(),(req,res)=>{const q=String(req.query.search||'').toLowerCase();res.json(products.filter(p=>!q||[p.name,p.sku,p.category,p.location].some(v=>v.toLowerCase().includes(q))));});
app.post('/products',auth(['Admin','Warehouse']),(req,res)=>{const p=productSchema.safeParse(req.body);if(!p.success)return res.status(400).json({error:p.error.issues[0].message});if(products.some(x=>x.sku===p.data.sku))return res.status(409).json({error:'SKU already exists.'});const x={...p.data,id:uid('p')};products.push(x);res.status(201).json(x)});
app.put('/products/:id',auth(['Admin','Warehouse']),(req,res)=>{const i=products.findIndex(x=>x.id===req.params.id),p=productSchema.safeParse(req.body);if(i<0)return res.status(404).json({error:'Product not found.'});if(!p.success)return res.status(400).json({error:p.error.issues[0].message});products[i]={...products[i],...p.data};res.json(products[i])});
const movementList=(_:Request,res:Response)=>res.json(movements.slice().reverse().map(m=>({...m,product:products.find(p=>p.id===m.productId)?.name||'Unknown'})));
const createMovement=(req:Request,res:Response)=>{const p=z.object({productId:z.string(),quantity:z.number().int().positive(),type:z.enum(['IN','OUT']),reason:z.string().min(2)}).safeParse(req.body);if(!p.success)return res.status(400).json({error:p.error.issues[0].message});const product=products.find(x=>x.id===p.data.productId);if(!product)return res.status(404).json({error:'Product not found.'});if(p.data.type==='OUT'&&product.stock<p.data.quantity)return res.status(422).json({error:'Insufficient stock; inventory cannot go negative.'});product.stock+=p.data.type==='IN'?p.data.quantity:-p.data.quantity;const m={id:uid('m'),...p.data,createdBy:req.user!.name,createdAt:new Date().toISOString()};movements.push(m);res.status(201).json(m)};
app.get(['/movements','/stock/movements'],auth(),movementList);
app.post(['/movements','/stock/movements'],auth(['Admin','Warehouse']),createMovement);
app.get('/challans',auth(),(_,res)=>res.json(challans.slice().reverse()));
app.get('/challans/:id',auth(),(req,res)=>{const c=challans.find(x=>x.id===req.params.id);return c?res.json(c):res.status(404).json({error:'Challan not found.'})});
app.post('/challans',auth(['Admin','Sales']),(req,res)=>{const p=z.object({customerId:z.string(),items:z.array(z.object({productId:z.string(),quantity:z.number().int().positive()})).min(1)}).safeParse(req.body);if(!p.success)return res.status(400).json({error:p.error.issues[0].message});if(!customers.some(c=>c.id===p.data.customerId))return res.status(404).json({error:'Customer not found.'});const items=[] as Challan['items'];for(const input of p.data.items){const product=products.find(x=>x.id===input.productId);if(!product)return res.status(404).json({error:'Product not found.'});items.push({productId:product.id,name:product.name,sku:product.sku,price:product.unitPrice,quantity:input.quantity})}const c:Challan={id:uid('ch'),number:`CH-${new Date().getFullYear()}-${String(challans.length+1).padStart(4,'0')}`,customerId:p.data.customerId,items,status:'Draft',createdBy:req.user!.name,createdAt:new Date().toISOString()};challans.push(c);res.status(201).json(c)});
app.patch('/challans/:id/confirm',auth(['Admin','Sales']),(req,res)=>{const c=challans.find(x=>x.id===req.params.id);if(!c)return res.status(404).json({error:'Challan not found.'});if(c.status!=='Draft')return res.status(409).json({error:`Only draft challans can be confirmed (current status: ${c.status}).`});for(const item of c.items){const product=products.find(p=>p.id===item.productId);if(!product)return res.status(409).json({error:`Product for ${item.name} is no longer available.`});if(product.stock<item.quantity)return res.status(422).json({error:`Insufficient stock for ${product.name}. Available: ${product.stock}, requested: ${item.quantity}.`})}c.status='Confirmed';for(const item of c.items){const product=products.find(p=>p.id===item.productId)!;product.stock-=item.quantity;movements.push({id:uid('m'),productId:product.id,quantity:item.quantity,type:'OUT',reason:`Confirmed challan ${c.number}`,createdBy:req.user!.name,createdAt:new Date().toISOString()})}res.json(c)});
app.patch('/challans/:id/cancel',auth(['Admin','Sales']),(req,res)=>{const c=challans.find(x=>x.id===req.params.id);if(!c)return res.status(404).json({error:'Challan not found.'});if(c.status==='Confirmed')return res.status(409).json({error:'Confirmed challans cannot be cancelled because inventory has already moved.'});if(c.status==='Cancelled')return res.status(409).json({error:'Challan is already cancelled.'});c.status='Cancelled';res.json(c)});
app.use((_:Request,res:Response)=>res.status(404).json({error:'Route not found.'}));
async function start(){try{await checkDatabaseConnection();console.log('Neon PostgreSQL connection established.');}catch(error){console.error('Unable to connect to Neon PostgreSQL. Check DATABASE_URL and network access.',error instanceof Error?error.message:'');}app.listen(PORT,()=>console.log(`Mini ERP API listening on :${PORT}`));}
void start();
